### ISSUE TITLE
possible to get migrate older slackarchive.io data?

### ISSUE THREAD

**Issue by psifertex** [dutchcoders/slackarchive#4]
I'd like to migrate my older binaryninja.slackarchive.io data. Is that possible?

**Comment by nl5887** [comment]
Easiest will be to export an archive from Slack, and import it using the SlackArchive importer.

**Comment by patcon** [comment]
Perhaps someone could could write a PR for an exporter, and maybe @nl5887 would be willing to deploy it?

**Comment by nl5887** [comment]
I always believed that he exported file contained complete histories. Because of the ongoing server costs and coming GDPR I'd like shut everything down before May 25th. If someone creates an exporter for both Elasticsearch and MongoDB to file, I'll be happy to put the archives onto S3. We can use a hash of the originating token as filename, which enables only authorised people to download.

**Comment by noisymime** [comment]
FWIW I just checked my Slack export and it definitely contains the full history, not just what is available through the web/app history. Approx. 300k messages on a free team.

**Comment by nl5887** [comment]
Thanks, that was what I expected. So the need for an exporter is no longer necessary I assume?

**Comment by yanokwa** [comment]
@nl5887 I think this issue can be closed 😀
